curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/danxiaonuo/gwf/china_ip.txt'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/danxiaonuo/gwf/china_ipv4.txt'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/danxiaonuo/gwf/china_ipv6.txt'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/danxiaonuo/gwf/gfwlist.txt'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/danxiaonuo/gwf/smartdns_gfw_domain.conf'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/danxiaonuo/gwf/smartdns_xiaonuo_domain.conf'
curl -s -m 3 --retry-delay 3 --retry 3 -k -4 --header 'cache-control: no-cache' --url 'https://purge.jsdelivr.net/gh/danxiaonuo/gwf/Country.mmdb'
