#=================================================
# https://github.com/danxiaonuo/gwf
# Description: Build gwf using GitHub Actions
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

name: 自动更新GWF库

# 设置触发条件
on:
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'build gwf'
        required: true
        default: 'build gwf'
  # 定时触发编译(每天早5点)
  schedule:
     - cron: '*/30 * * * *'
  # 点☆Star触发开始编译
  watch:  
     types: [started]
   
# 任务集
jobs:
  gwf:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    
    # 运行步骤
    steps:
    
    # 检出各个代码模块
    - name: 检出各个代码模块
      uses: actions/checkout@v3
    
    # 自动更新IP库
    - name: 自动更新GWF库
      run: |
          bash default/gwf.sh
    
    # 自动上传     
    - name: 自动上传
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update GWF
        skip_dirty_check: false
        commit_user_name: Action Bot
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: Action <actions@github.com>
    
    # 清理缓存
    - name: 自动更新GWF库缓存
      run: |
        bash default/purge.sh
    
    # 删除旧的GitHub-workflow    
    - name: 删除旧的GitHub-workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1    #保留多少个workflow不删除
